name: Hello world

on: 
  push:
   branches:
   - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build job steps
        run: echo "name is, ${{ vars.MY_NAME}}"

  
 
